site_name: Samsung Galaxy Store Docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - Samsung Galaxy Store Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md