[tool.poetry]
name = "samsung-galaxy-store"
version = "0.1.5"
description = "Samsung Galaxy Store analysis tools"
authors = ["Kevin Ramdath <krpent@gmail.com>"]
repository = "https://github.com/minormending/samsung-galaxy-store"
readme = "README.md"
license = "MIT"
keywords = ["samsung", "galaxy", "appstore"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.3.0"
nose2 = "^0.11.0"

[tool.poetry.scripts]
galaxy-store-cli = "samsung_galaxy_store.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
